### ISSUE TITLE
Bonsai2 does not compile with newer CMake/CUDA

### ISSUE THREAD

**Issue by LourensVeen** [treecode/Bonsai2#1]
I'm working on renovating the AMUSE build system, and it seems that Bonsai and Bonsai2 have been broken for a while. I'd like to discuss what to do with them.

The original Bonsai uses an obsolete CUDA texture API that has been removed in IIRC CUDA 11. Bonsai2 has moved away from that it seems, but doesn't build because the way CMake detects CUDA has changed, and the CMake configuration needs an update. It seems like getting Bonsai2 to work again would not be an unreasonable amount of work.

Would it make sense to remove Bonsai from AMUSE, but fix up Bonsai2 to work again? Is there anything that Bonsai can do that Bonsai2 doesn't?

**Comment by jbedorf** [comment]
Hi Lourens, 

Bonsai2 was never productized so it will lack a lot of required features to integrate with AMUSE. I [recently updated](https://github.com/treecode/Bonsai/pull/52) Bonsai to be compatible with CUDA 11+ versions by the removal of the textures. When I tested that all the compilation and execution steps worked, so not quite sure what the CMAKE issues are that you are phasing.

**Comment by LourensVeen** [comment]
Ah, I didn't realise that there was a newer version of Bonsai. We'd like to keep Bonsai in AMUSE, so I'll probably try to update to the latest version then. Thanks!

As for Bonsai2, it uses `FIND_PACKAGE(CUDA)` which is [deprecated](https://cmake.org/cmake/help/latest/module/FindCUDA.html) and doesn't work on newer CMakes anymore, although you can still manually enable it.

**Comment by LourensVeen** [comment]
Ugh, I've just discovered that what is called `bonsai2` in AMUSE isn't Bonsai2, it's just a newer version of Bonsai. Looks like I fell into a pit again. (Less unpleasant than being eaten by a grue I guess, but urgh.)

So it looks like Bonsai2 was actually never in AMUSE, which is probably what you meant above. And what we have is a very old pre-Github version of Bonsai, as `bonsai`, and a newer version from January 2019 as `bonsai2`.
 
So what probably needs to happen is that we remove `bonsai`, and update `bonsai2` to the latest release of Bonsai. Ideally, we'd rename it back to `bonsai` too, and install a shim to make sure that scripts using `bonsai2` still work.

I'm going to close this here, because it seems that there isn't anything wrong with Bonsai itself, and anyway it's in the wrong repo. Thanks, sorry for the confusion!

**Comment by jbedorf** [comment]
No problem. Feel free to open a ticket in the other repo if there's further questions.
